$kind: http-request
auth:
  type: bearer
  credentials:
    token: "{{access_token}}"
examples: .resources/Bulk Update Settings.resources/examples
order: 2000
method: PUT
url: "{{base_url}}/api/v1/settings"
headers:
  Accept: application/json
  Content-Type: application/json
body:
  type: json
  content: |-
    {
      "settings": {
        "numbering.receipt_prefix": "RCPT",
        "numbering.transfer_prefix": "TRF"
      }
    }
